-- MySQL Script generated by MySQL Workbench
-- Tue May 23 18:50:02 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ppap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ppap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ppap` DEFAULT CHARACTER SET utf8 ;
USE `ppap` ;

-- -----------------------------------------------------
-- Table `ppap`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ppap`.`pedidos` (
  `idpedidos` INT NOT NULL AUTO_INCREMENT,
  `customer_group` VARCHAR(50) NULL,
  `customer` VARCHAR(45) NULL,
  `contact_name` VARCHAR(45) NULL,
  `lf_coordinator` VARCHAR(45) NULL,
  `customer_part_number` VARCHAR(45) NULL,
  `lf_part_number` VARCHAR(45) NULL,
  `group` VARCHAR(45) NULL,
  `note_oem_part_number` VARCHAR(45) NULL,
  `level_request` VARCHAR(45) NULL,
  `type_of_request` VARCHAR(45) NULL,
  `etr` VARCHAR(45) NULL,
  `date_request` DATE NULL,
  `customer_due_date` DATE NULL,
  `lf_due_date` DATE NULL,
  `submited_date` DATE NULL,
  `full_interim_submission` VARCHAR(45) NULL,
  `day_submitted` DATE NULL,
  `why_open` VARCHAR(45) NULL,
  `pass_due_vs_lf_due_date` VARCHAR(45) NULL,
  `time_to_response` INT NULL,
  `comments` VARCHAR(300) NULL,
  `approval_date` DATE NULL,
  `type_of_no_conformity` VARCHAR(45) NULL,
  `no_conformidad_de_submision_de_ppaps` VARCHAR(45) NULL,
  `imds_submission` VARCHAR(45) NULL,
  PRIMARY KEY (`idpedidos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
